version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eslint-plugin-json"
        versions: ["3.x"]
    assignees:
      - "FlorentinTh"
