version: '3'

services:
  le2ml-api:
    image: 'le2ml-api:latest'
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.certs:/.certs
      - ./log:/log
      - ./data:/data
    network_mode: bridge
