version: '3'

services:
  mongo:
    image: 'mongo:4.2'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  redis:
    image: 'redis:5.0'
    command: redis-server --requirepass password
    restart: always
    ports:
      - 6379:6379
