name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

        node-version:
          - 14
          - 16

    name: Using Node ${{ matrix.node-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rename .env.example
        run: mv .env.example .env

      - name: Setup node ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update npm to v7.x
        run: npm i -g npm@latest --registry=https://registry.npmjs.org

      - name: Install project dependencies
        run: npm ci

      - name: Build project
        run: npm run build
